spring:
  datasource:
    url: jdbc:postgresql://postgres:55432/socialnetwork
    username: sn
    password: sn
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
  sql:
    init:
      mode: never
  data:
    redis:
      host: redis
      port: 6379
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: social-network
      env: local
    enable:
      jvm: true        # métricas JVM
      jdbc: true       # métricas JDBC
      hikaricp: true   # métricas de pool Hikari
      tomcat: true
      logback: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
      sla:
        "[http.server.requests]": 50ms,100ms,250ms,500ms,1s,5s
  prometheus:
    metrics:
      export:
        enabled: true

info:
  app:
    name: socialnetwork
    version: ${spring.application.version:${project.version:dev}}
